"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { Icon } from "@/components/Icon";
import type { OperationsCalendarData, OperationsCalendarEvent } from "../calendar-service";

type View = "month" | "week" | "agenda";
const weekdays = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
const eventTime = (value: string) => new Intl.DateTimeFormat("en-GB", { timeZone: "Africa/Harare", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(value));
const fullDate = (key: string) => new Intl.DateTimeFormat("en-GB", { timeZone: "UTC", weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date(`${key}T00:00:00Z`));
const shortDate = (key: string) => new Intl.DateTimeFormat("en-GB", { timeZone: "UTC", weekday: "short", day: "numeric", month: "short" }).format(new Date(`${key}T00:00:00Z`));

export function OperationsCalendar({ data }: { data: OperationsCalendarData }) {
  const router = useRouter(); const pathname = usePathname();
  const defaultSelected = data.days.some((day) => day.key === data.todayKey && day.inMonth) ? data.todayKey : `${data.monthKey}-01`;
  const [view, setView] = useState<View>("month"); const [selectedDate, setSelectedDate] = useState(defaultSelected); const [filter, setFilter] = useState<"all" | "meeting" | "duty">("all"); const [selectedEvent, setSelectedEvent] = useState<OperationsCalendarEvent | null>(null);
  const visibleEvents = useMemo(() => filter === "all" ? data.events : data.events.filter((event) => event.kind === filter), [data.events, filter]);
  const eventsByDate = useMemo(() => { const map = new Map<string, OperationsCalendarEvent[]>(); for (const event of visibleEvents) map.set(event.dateKey, [...(map.get(event.dateKey) ?? []), event]); return map; }, [visibleEvents]);
  const selectedEvents = eventsByDate.get(selectedDate) ?? [];

  function navigateMonth(delta: number) { const [year, month] = data.monthKey.split("-").map(Number); const target = new Date(Date.UTC(year, month - 1 + delta, 1)); router.push(`${pathname}?month=${target.toISOString().slice(0, 7)}`); }
  function goToday() { router.push(`${pathname}?month=${data.todayKey.slice(0, 7)}`); setSelectedDate(data.todayKey); }
  const selectedIndex = Math.max(0, data.days.findIndex((day) => day.key === selectedDate)); const weekStart = Math.floor(selectedIndex / 7) * 7; const weekDays = data.days.slice(weekStart, weekStart + 7);

  return <div className="space-y-5">
    <section className="overflow-hidden rounded-3xl border border-[#343431] bg-[#1d1d1b] shadow-[0_20px_70px_rgba(0,0,0,.2)]">
      <div className="flex flex-col gap-4 border-b border-[#343431] p-5 xl:flex-row xl:items-center xl:justify-between">
        <div className="flex items-center gap-3"><div className="flex items-center rounded-xl border border-[#3b3b38] bg-[#171716] p-1"><button aria-label="Previous month" onClick={() => navigateMonth(-1)} className="rounded-lg p-2 text-[#999] hover:bg-[#292927] hover:text-white"><Icon name="chevron" className="h-4 w-4 rotate-180"/></button><button onClick={goToday} className="rounded-lg px-3 py-2 text-xs font-semibold text-[#ccc] hover:bg-[#292927]">Today</button><button aria-label="Next month" onClick={() => navigateMonth(1)} className="rounded-lg p-2 text-[#999] hover:bg-[#292927] hover:text-white"><Icon name="chevron" className="h-4 w-4"/></button></div><div><h2 className="text-xl font-semibold tracking-[-.02em] text-white">{data.monthLabel}</h2><p className="mt-1 text-[10px] uppercase tracking-[.12em] text-[#6f6f69]">Africa/Harare · Personal operations calendar</p></div></div>
        <div className="flex flex-wrap items-center gap-2"><div className="flex rounded-xl border border-[#3b3b38] bg-[#171716] p-1">{(["month", "week", "agenda"] as const).map((item) => <button key={item} onClick={() => setView(item)} className={`rounded-lg px-3 py-2 text-[10px] font-semibold capitalize ${view === item ? "bg-[#333330] text-white" : "text-[#777] hover:text-[#bbb]"}`}>{item}</button>)}</div><Link href={`/team/meetings?create=1&date=${selectedDate}`} className="flex items-center gap-2 rounded-xl bg-sunset px-4 py-2.5 text-xs font-semibold text-white"><Icon name="plus" className="h-4 w-4"/>New meeting</Link></div>
      </div>
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#30302d] px-5 py-3"><div className="flex gap-2">{(["all", "meeting", "duty"] as const).map((item) => <button key={item} onClick={() => setFilter(item)} className={`flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-[10px] font-semibold capitalize ${filter === item ? "border-[#555] bg-[#30302d] text-white" : "border-[#363633] text-[#777]"}`}>{item !== "all" && <span className={`h-1.5 w-1.5 rounded-full ${item === "meeting" ? "bg-gold" : "bg-savannah"}`}/>} {item === "all" ? "All events" : `${item}s`}</button>)}</div><p className="text-[10px] text-[#6f6f69]">{visibleEvents.length} event{visibleEvents.length === 1 ? "" : "s"} in this calendar range</p></div>
      {view === "month" && <MonthGrid days={data.days} eventsByDate={eventsByDate} selectedDate={selectedDate} selectDate={setSelectedDate} selectEvent={setSelectedEvent}/>} 
      {view === "week" && <WeekGrid days={weekDays} eventsByDate={eventsByDate} selectedDate={selectedDate} selectDate={setSelectedDate} selectEvent={setSelectedEvent}/>} 
      {view === "agenda" && <Agenda events={visibleEvents} selectEvent={setSelectedEvent}/>} 
    </section>
    <section className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="rounded-2xl border border-[#343431] bg-[#1d1d1b] p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-victoria">Selected day</p><h3 className="mt-2 text-base font-semibold text-white">{fullDate(selectedDate)}</h3></div><Link href={`/team/meetings?create=1&date=${selectedDate}`} className="text-[10px] font-semibold text-sunset">Schedule meeting</Link></div><div className="mt-4 divide-y divide-[#30302d]">{selectedEvents.map((event) => <button key={event.id} onClick={() => setSelectedEvent(event)} className="flex w-full items-center gap-3 py-3 text-left"><span className={`h-8 w-1 rounded-full ${event.kind === "meeting" ? "bg-gold" : "bg-savannah"}`}/><span className="w-12 text-xs font-semibold text-[#999]">{eventTime(event.startsAt)}</span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold text-[#ddd]">{event.title}</span><span className="mt-1 block truncate text-[10px] text-[#70706a]">{event.location}</span></span><span className="rounded-full bg-[#2b2b29] px-2 py-1 text-[9px] capitalize text-[#999]">{event.kind}</span></button>)}{!selectedEvents.length && <p className="py-10 text-center text-xs text-[#70706a]">No meetings or duties on this day.</p>}</div></div><div className="rounded-2xl border border-[#343431] bg-[#181816] p-5"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#777]">Calendar summary</p><div className="mt-4 space-y-3">{[{ label: "Meetings", value: visibleEvents.filter((event) => event.kind === "meeting").length, tone: "bg-gold" }, { label: "Duties", value: visibleEvents.filter((event) => event.kind === "duty").length, tone: "bg-savannah" }, { label: "Awaiting response", value: visibleEvents.filter((event) => event.kind === "meeting" && event.status === "needs_action").length, tone: "bg-sunset" }].map((item) => <div key={item.label} className="flex items-center justify-between rounded-xl bg-[#242422] px-4 py-3"><span className="flex items-center gap-2 text-xs text-[#aaa]"><span className={`h-2 w-2 rounded-full ${item.tone}`}/>{item.label}</span><strong className="text-sm text-white">{item.value}</strong></div>)}</div></div></section>
    {selectedEvent && <EventDialog event={selectedEvent} close={() => setSelectedEvent(null)}/>} 
  </div>;
}

function MonthGrid({ days, eventsByDate, selectedDate, selectDate, selectEvent }: { days: OperationsCalendarData["days"]; eventsByDate: Map<string, OperationsCalendarEvent[]>; selectedDate: string; selectDate: (key: string) => void; selectEvent: (event: OperationsCalendarEvent) => void }) { return <div className="overflow-x-auto"><div className="min-w-225"><div className="grid grid-cols-7 border-b border-[#30302d] bg-[#181816]">{weekdays.map((day) => <div key={day} className="px-3 py-3 text-center text-[10px] font-bold uppercase tracking-[.12em] text-[#686862]">{day}</div>)}</div><div className="grid grid-cols-7">{days.map((day) => <div key={day.key} onClick={() => selectDate(day.key)} className={`min-h-32 cursor-pointer border-b border-r border-[#30302d] p-2 transition hover:bg-[#242422] ${!day.inMonth ? "bg-[#171716] opacity-50" : "bg-[#1d1d1b]"} ${selectedDate === day.key ? "ring-1 ring-inset ring-victoria/60" : ""}`}><div className={`grid h-7 w-7 place-items-center rounded-full text-xs font-semibold ${day.isToday ? "bg-sunset text-white" : "text-[#aaa]"}`}>{day.day}</div><div className="mt-2 space-y-1">{(eventsByDate.get(day.key) ?? []).slice(0, 3).map((event) => <button key={event.id} onClick={(click) => { click.stopPropagation(); selectEvent(event); }} className={`block w-full truncate rounded-md border-l-2 px-2 py-1.5 text-left text-[9px] font-medium ${event.kind === "meeting" ? "border-gold bg-gold/8 text-[#e8c77e]" : "border-savannah bg-savannah/8 text-[#8bcbae]"}`}><span className="mr-1 opacity-70">{eventTime(event.startsAt)}</span>{event.title}</button>)}{(eventsByDate.get(day.key) ?? []).length > 3 && <p className="px-1 text-[9px] text-[#777]">+{(eventsByDate.get(day.key) ?? []).length - 3} more</p>}</div></div>)}</div></div></div>; }

function WeekGrid({ days, eventsByDate, selectedDate, selectDate, selectEvent }: { days: OperationsCalendarData["days"]; eventsByDate: Map<string, OperationsCalendarEvent[]>; selectedDate: string; selectDate: (key: string) => void; selectEvent: (event: OperationsCalendarEvent) => void }) { return <div className="overflow-x-auto p-4"><div className="grid min-w-190 grid-cols-7 gap-3">{days.map((day) => <div key={day.key} onClick={() => selectDate(day.key)} className={`min-h-100 cursor-pointer rounded-xl border p-3 ${selectedDate === day.key ? "border-victoria/60 bg-victoria/5" : "border-[#353532] bg-[#20201e]"}`}><p className="text-[10px] font-bold uppercase tracking-wider text-[#777]">{shortDate(day.key)}</p><div className="mt-4 space-y-2">{(eventsByDate.get(day.key) ?? []).map((event) => <button key={event.id} onClick={(click) => { click.stopPropagation(); selectEvent(event); }} className={`w-full rounded-lg border p-2 text-left ${event.kind === "meeting" ? "border-gold/20 bg-gold/8" : "border-savannah/20 bg-savannah/8"}`}><p className="text-[9px] font-semibold text-[#999]">{eventTime(event.startsAt)}</p><p className="mt-1 text-[10px] font-semibold text-[#ddd]">{event.title}</p><p className="mt-1 truncate text-[9px] text-[#777]">{event.location}</p></button>)}{!(eventsByDate.get(day.key) ?? []).length && <p className="pt-10 text-center text-[9px] text-[#555]">Open</p>}</div></div>)}</div></div>; }

function Agenda({ events, selectEvent }: { events: OperationsCalendarEvent[]; selectEvent: (event: OperationsCalendarEvent) => void }) { const groups = Array.from(new Set(events.map((event) => event.dateKey))); return <div className="p-5">{groups.length ? <div className="space-y-6">{groups.map((key) => <section key={key}><h3 className="text-xs font-semibold text-white">{fullDate(key)}</h3><div className="mt-2 divide-y divide-[#30302d] rounded-xl border border-[#343431] bg-[#20201e]">{events.filter((event) => event.dateKey === key).map((event) => <button key={event.id} onClick={() => selectEvent(event)} className="flex w-full items-center gap-4 p-4 text-left hover:bg-[#292927]"><span className="w-12 text-xs font-semibold text-victoria">{eventTime(event.startsAt)}</span><span className={`h-8 w-1 rounded-full ${event.kind === "meeting" ? "bg-gold" : "bg-savannah"}`}/><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-[#ddd]">{event.title}</span><span className="mt-1 block text-xs text-[#777]">{event.location}</span></span><span className="rounded-full bg-[#333] px-2 py-1 text-[9px] capitalize text-[#aaa]">{event.status.replace("_", " ")}</span></button>)}</div></section>)}</div> : <p className="py-20 text-center text-sm text-[#6f6f69]">No events in this calendar range.</p>}</div>; }

function EventDialog({ event, close }: { event: OperationsCalendarEvent; close: () => void }) { return <div className="fixed inset-0 z-60 grid place-items-center bg-black/70 p-5 backdrop-blur-sm" onClick={close}><article onClick={(click) => click.stopPropagation()} className="w-full max-w-lg rounded-3xl border border-[#41413d] bg-[#1d1d1b] p-6 shadow-2xl"><div className="flex items-start justify-between"><span className={`rounded-full px-2.5 py-1 text-[9px] font-bold uppercase tracking-wider ${event.kind === "meeting" ? "bg-gold/10 text-gold" : "bg-savannah/10 text-savannah"}`}>{event.kind}</span><button onClick={close} aria-label="Close event" className="rounded-lg p-2 text-[#777] hover:bg-[#292927]"><Icon name="close" className="h-4 w-4"/></button></div><h2 className="mt-5 text-xl font-semibold text-white">{event.title}</h2><div className="mt-4 grid gap-3 rounded-xl bg-[#242422] p-4 text-xs text-[#aaa]"><p className="flex items-center gap-2"><Icon name="calendar" className="h-4 w-4 text-victoria"/>{fullDate(event.dateKey)} · {eventTime(event.startsAt)}{event.endsAt ? `–${eventTime(event.endsAt)}` : ""}</p><p className="flex items-center gap-2"><Icon name="pin" className="h-4 w-4 text-victoria"/>{event.location}</p><p className="flex items-center gap-2"><Icon name="shield" className="h-4 w-4 text-victoria"/>Status: {event.status.replace("_", " ")}</p></div>{event.description && <p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-[#999]">{event.description}</p>}<Link href={event.href} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-sunset px-4 py-3 text-xs font-semibold text-white">Open {event.kind === "meeting" ? "meeting" : "duty"}<Icon name="arrow" className="h-4 w-4"/></Link></article></div>; }
