"use client";

import { useState, useTransition } from "react";
import { Icon } from "@/components/Icon";
import type { HaroldConversation, HaroldMessage } from "../harold-service";
import { sendHaroldMessage } from "../harold-actions";

export function HaroldChat({ organizationId, initialConversations }: { organizationId: string; initialConversations: HaroldConversation[] }) {
  const [conversations, setConversations] = useState(initialConversations); const [selectedId, setSelectedId] = useState(initialConversations[0]?.id ?? ""); const [input, setInput] = useState(""); const [pending, startTransition] = useTransition(); const [error, setError] = useState<string | null>(null);
  const selected = conversations.find((conversation) => conversation.id === selectedId);
  function submit(event: React.FormEvent) { event.preventDefault(); const content = input.trim(); if (!content) return; setInput(""); setError(null); startTransition(async () => { try { const result = await sendHaroldMessage(organizationId, { conversationId: selectedId || undefined, message: content }); setSelectedId(result.conversationId); setConversations((current) => { const existing = current.find((conversation) => conversation.id === result.conversationId); if (existing) return current.map((conversation) => conversation.id === result.conversationId ? { ...conversation, messages: [...conversation.messages, result.message as HaroldMessage] } : conversation); return [{ id: result.conversationId, title: content.slice(0, 60), createdAt: result.message.createdAt, updatedAt: result.message.createdAt, messages: [result.message as HaroldMessage] }, ...current]; }); } catch (cause) { setInput(content); setError(cause instanceof Error ? cause.message : "Unable to save message."); } }); }
  return <div className="overflow-hidden rounded-2xl border border-[#343431] bg-[#1d1d1b] lg:grid lg:min-h-150 lg:grid-cols-[260px_1fr]"><aside className="border-b border-[#343431] bg-[#181816] p-4 lg:border-b-0 lg:border-r"><button onClick={() => setSelectedId("")} className="flex w-full items-center justify-center gap-2 rounded-xl border border-[#3b3b38] px-3 py-2.5 text-xs font-semibold text-[#d2d2cb]"><Icon name="plus" className="h-4 w-4"/>New conversation</button><div className="mt-4 space-y-1">{conversations.map((conversation) => <button key={conversation.id} onClick={() => setSelectedId(conversation.id)} className={`w-full truncate rounded-lg px-3 py-2 text-left text-xs ${selectedId === conversation.id ? "bg-[#30302d] text-white" : "text-[#888882] hover:bg-[#242422]"}`}>{conversation.title}</button>)}{!conversations.length && <p className="px-3 py-5 text-center text-[10px] text-[#666]">No saved conversations.</p>}</div></aside><div className="flex min-h-120 flex-col"><div className="flex items-center justify-between border-b border-[#343431] px-5 py-4"><div><p className="text-sm font-semibold text-white">{selected?.title ?? "New conversation"}</p><p className="mt-1 text-[10px] text-[#74746e]">Messages are saved to your private history.</p></div><span className="rounded-full border border-gold/30 bg-gold/10 px-2.5 py-1 text-[9px] font-bold uppercase tracking-wider text-gold">AI not connected</span></div><div className="flex-1 space-y-3 p-5">{selected?.messages.map((message) => <div key={message.id} className={`flex ${message.role === "user" ? "justify-end" : "justify-start"}`}><div className={`max-w-xl rounded-xl px-4 py-3 text-sm ${message.role === "user" ? "bg-sunset text-white" : "bg-[#292927] text-[#ccc]"}`}>{message.content}</div></div>)}{(!selected || !selected.messages.length) && <div className="grid min-h-72 place-items-center text-center"><div><Icon name="sparkles" className="mx-auto h-7 w-7 text-victoria"/><p className="mt-4 text-sm font-semibold text-white">Start a real conversation record</p><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-[#777771]">Your messages will be saved. Harold cannot answer yet because the AI service has not been connected.</p></div></div>}<div className="rounded-xl border border-victoria/20 bg-victoria/5 px-4 py-3 text-xs text-[#8dbed0]"><strong>System:</strong> Harold AI is not connected yet. No generated response will be added.</div>{error && <p className="text-xs text-sunset">{error}</p>}</div><form onSubmit={submit} className="flex gap-2 border-t border-[#343431] p-4"><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="Save a message for Harold…" className="input flex-1"/><button disabled={pending || !input.trim()} className="rounded-xl bg-victoria px-4 text-white disabled:opacity-50"><Icon name="send" className="h-4 w-4"/></button></form></div></div>;
}
