"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/Icon";
import type { OrganizationStructureData } from "../organization-service";
import { createDepartment, createLocation, createTeam, setStructureActive } from "../organization-actions";

export function OrganizationStructure({ organizationId, data }: { organizationId: string; data: OrganizationStructureData }) {
  const router = useRouter(); const [open, setOpen] = useState<"department" | "location" | "team" | null>(null); const [pending, startTransition] = useTransition(); const [error, setError] = useState<string | null>(null);
  const run = (action: () => Promise<unknown>, close = false) => startTransition(async () => { try { setError(null); await action(); if (close) setOpen(null); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update structure."); } });
  return <div className="space-y-5">{error && <p className="rounded-xl border border-sunset/30 bg-sunset/10 px-4 py-3 text-xs text-sunset">{error}</p>}<div className="flex flex-wrap gap-2">{(["department", "location", "team"] as const).map((item) => <button key={item} onClick={() => setOpen(open === item ? null : item)} className="flex items-center gap-2 rounded-xl border border-[#444] bg-[#242422] px-4 py-2.5 text-xs font-semibold capitalize text-[#ddd]"><Icon name="plus" className="h-4 w-4"/>Add {item}</button>)}</div>{open && <CreateStructureForm kind={open} data={data} pending={pending} submit={(input) => run(() => open === "department" ? createDepartment(organizationId, input) : open === "location" ? createLocation(organizationId, input) : createTeam(organizationId, input), true)}/>}<div className="grid gap-5 xl:grid-cols-3"><StructureCard title="Departments" items={data.departments.map((item) => ({ id: item.id, title: item.name, detail: item.description ?? "No description", meta: `${item.memberCount} active staff`, active: item.active }))} toggle={(id, active) => run(() => setStructureActive(organizationId, "departments", id, active))}/><StructureCard title="Locations" items={data.locations.map((item) => ({ id: item.id, title: `${item.name} · ${item.code}`, detail: item.address ?? item.timezone, meta: `${item.memberCount} active staff`, active: item.active }))} toggle={(id, active) => run(() => setStructureActive(organizationId, "locations", id, active))}/><StructureCard title="Teams" items={data.teams.map((item) => ({ id: item.id, title: item.name, detail: item.departmentName, meta: `${item.memberCount} members`, active: item.active }))} toggle={(id, active) => run(() => setStructureActive(organizationId, "teams", id, active))}/></div></div>;
}

function StructureCard({ title, items, toggle }: { title: string; items: Array<{ id: string; title: string; detail: string; meta: string; active: boolean }>; toggle: (id: string, active: boolean) => void }) { return <section className="overflow-hidden rounded-2xl border border-[#343431] bg-[#1d1d1b]"><h2 className="border-b border-[#343431] px-5 py-4 text-base font-semibold text-white">{title}</h2><div className="divide-y divide-[#30302d]">{items.map((item) => <div key={item.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-[#e4e4de]">{item.title}</p><p className="mt-1 text-xs text-[#85857f]">{item.detail}</p><p className="mt-2 text-[10px] text-[#676761]">{item.meta}</p></div><button onClick={() => toggle(item.id, !item.active)} className={`rounded-full px-2.5 py-1 text-[9px] font-bold uppercase ${item.active ? "bg-savannah/10 text-savannah" : "bg-[#333] text-[#888]"}`}>{item.active ? "Active" : "Inactive"}</button></div></div>)}{!items.length && <p className="px-5 py-10 text-center text-xs text-[#777]">Nothing configured yet.</p>}</div></section>; }

function CreateStructureForm({ kind, data, pending, submit }: { kind: "department" | "location" | "team"; data: OrganizationStructureData; pending: boolean; submit: (input: Record<string, FormDataEntryValue | undefined>) => void }) { return <form className="grid gap-4 rounded-2xl border border-[#40403c] bg-[#1d1d1b] p-5 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); submit({ name: form.get("name") ?? undefined, description: form.get("description") ?? undefined, code: form.get("code") ?? undefined, address: form.get("address") ?? undefined, timezone: form.get("timezone") ?? undefined, departmentId: form.get("departmentId") || undefined }); }}><label className="space-y-2"><span className="text-xs text-[#888]">Name</span><input name="name" required className="input"/></label>{kind === "location" && <><label className="space-y-2"><span className="text-xs text-[#888]">Code</span><input name="code" required className="input"/></label><label className="space-y-2"><span className="text-xs text-[#888]">Address</span><input name="address" className="input"/></label><label className="space-y-2"><span className="text-xs text-[#888]">Timezone</span><select name="timezone" defaultValue="Africa/Harare" className="input"><option value="Africa/Harare">Africa/Harare</option><option value="Africa/Johannesburg">Africa/Johannesburg</option><option value="UTC">UTC</option></select></label></>}{kind === "team" && <label className="space-y-2"><span className="text-xs text-[#888]">Department</span><select name="departmentId" className="input"><option value="">Unassigned</option>{data.departments.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}{kind !== "location" && <label className="space-y-2 sm:col-span-2"><span className="text-xs text-[#888]">Description</span><textarea name="description" rows={3} className="input"/></label>}<div className="sm:col-span-2 flex justify-end"><button disabled={pending} className="rounded-xl bg-sunset px-5 py-2.5 text-xs font-semibold text-white">{pending ? "Saving…" : `Create ${kind}`}</button></div></form>; }
