"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/Icon";
import type { AnnouncementView } from "../communication-service";
import { publishAnnouncement } from "../communication-actions";

const format = (value: string) => new Intl.DateTimeFormat("en-GB", { timeZone: "Africa/Harare", day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value));

export function CommunicationBoard({ announcements, organizationId, canManage }: { announcements: AnnouncementView[]; organizationId: string; canManage: boolean }) {
  const [category, setCategory] = useState("all"); const [open, setOpen] = useState(false);
  const categories = Array.from(new Set(announcements.map((item) => item.category)));
  const filtered = useMemo(() => category === "all" ? announcements : announcements.filter((item) => item.category === category), [announcements, category]);
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><select value={category} onChange={(event) => setCategory(event.target.value)} className="input max-w-56"><option value="all">All categories</option>{categories.map((item) => <option key={item}>{item}</option>)}</select>{canManage && <button onClick={() => setOpen(!open)} className="flex items-center gap-2 rounded-xl bg-sunset px-4 py-2.5 text-xs font-semibold text-white"><Icon name="plus" className="h-4 w-4"/>Publish announcement</button>}</div>{open && <AnnouncementForm organizationId={organizationId} onDone={() => setOpen(false)}/>}<div className="grid gap-4 xl:grid-cols-2">{filtered.map((item) => <article key={item.id} className="rounded-2xl border border-[#343431] bg-[#1d1d1b] p-5"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-victoria/10 px-2.5 py-1 text-[9px] font-bold uppercase tracking-wider text-victoria">{item.category}</span><span className={`rounded-full px-2 py-1 text-[9px] font-semibold uppercase ${item.status === "active" ? "bg-savannah/10 text-savannah" : "bg-[#333] text-[#888]"}`}>{item.status}</span></div><h2 className="mt-4 text-base font-semibold text-white">{item.title}</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#aaa9a2]">{item.body}</p><div className="mt-5 border-t border-[#30302d] pt-3 text-[10px] text-[#71716b]"><p>{item.authorName} · {format(item.publishedAt)}</p>{item.expiresAt && <p className="mt-1">Expires {format(item.expiresAt)}</p>}</div></article>)}</div>{!filtered.length && <div className="rounded-2xl border border-dashed border-[#3b3b38] px-6 py-12 text-center text-xs text-[#777771]">No announcements in this category.</div>}<section className="rounded-2xl border border-[#30302e] bg-[#181816] p-5 opacity-70"><div className="flex items-center gap-3"><Icon name="communication" className="h-5 w-5 text-[#777]"/><div><p className="text-sm font-semibold text-[#b9b9b2]">Team chat coming later</p><p className="mt-1 text-xs text-[#6f6f69]">Chat will be activated when its message and channel model is ready.</p></div></div></section></div>;
}

function AnnouncementForm({ organizationId, onDone }: { organizationId: string; onDone: () => void }) { const router = useRouter(); const [pending, startTransition] = useTransition(); const [error, setError] = useState<string | null>(null); return <form className="grid gap-4 rounded-2xl border border-[#40403c] bg-[#1d1d1b] p-5 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); startTransition(async () => { try { setError(null); await publishAnnouncement(organizationId, { title: form.get("title"), category: form.get("category"), body: form.get("body"), expiresAt: form.get("expiresAt") ? new Date(String(form.get("expiresAt"))).toISOString() : undefined }); onDone(); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to publish."); } }); }}><label className="space-y-2"><span className="text-xs text-[#92928c]">Title</span><input name="title" required className="input"/></label><label className="space-y-2"><span className="text-xs text-[#92928c]">Category</span><input name="category" required defaultValue="Operations" className="input"/></label><label className="space-y-2"><span className="text-xs text-[#92928c]">Expiry date (optional)</span><input name="expiresAt" type="datetime-local" className="input"/></label><label className="space-y-2 sm:col-span-2"><span className="text-xs text-[#92928c]">Announcement</span><textarea name="body" required rows={5} className="input"/></label>{error && <p className="sm:col-span-2 text-xs text-sunset">{error}</p>}<div className="sm:col-span-2 flex justify-end"><button disabled={pending} className="rounded-xl bg-sunset px-5 py-2.5 text-xs font-semibold text-white">{pending ? "Publishing…" : "Publish"}</button></div></form>; }
