import type { getReportsData } from "../reports-service";

type Data = Awaited<ReturnType<typeof getReportsData>>;
const hours = (minutes: number) => `${Math.floor(minutes / 60)}h ${minutes % 60}m`;

export function ReportsView({ data }: { data: Data }) {
  const personalCards = [{ label: "Attendance days this month", value: data.personal.attendanceDays }, { label: "Hours worked this month", value: hours(data.personal.workedMinutes) }, { label: "Duties completed", value: `${data.personal.dutiesCompleted}/${data.personal.dutiesAssigned}` }, { label: "Upcoming meetings", value: data.personal.upcomingMeetings }, { label: "Active announcements", value: data.personal.announcements }, { label: "Published documents", value: data.personal.documents }];
  return <div className="space-y-8"><section><h2 className="text-lg font-semibold text-white">My summary</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{personalCards.map((card) => <div key={card.label} className="rounded-2xl border border-[#343431] bg-[#1d1d1b] p-5"><p className="text-xs text-[#85857f]">{card.label}</p><p className="mt-3 text-2xl font-semibold text-white">{card.value}</p></div>)}</div></section>{data.manager && <section><p className="text-xs font-semibold uppercase tracking-[.14em] text-gold">Manager view</p><h2 className="mt-2 text-lg font-semibold text-white">Team operations</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Active staff", value: data.manager.activeStaff }, { label: "Present today", value: data.manager.presentToday }, { label: "Absent today", value: data.manager.absentToday }, { label: "Duty completion", value: `${data.manager.dutiesCompleted}/${data.manager.dutiesAssigned}` }].map((card) => <div key={card.label} className="rounded-2xl border border-[#343431] bg-[#1d1d1b] p-5"><p className="text-xs text-[#85857f]">{card.label}</p><p className="mt-3 text-2xl font-semibold text-white">{card.value}</p></div>)}</div><div className="mt-4 overflow-hidden rounded-2xl border border-[#343431] bg-[#1d1d1b]"><div className="border-b border-[#343431] px-5 py-4 text-sm font-semibold text-white">Department attendance today</div>{data.manager.departmentSummary.length ? <div className="divide-y divide-[#30302d]">{data.manager.departmentSummary.map((department) => <div key={department.name} className="grid grid-cols-4 gap-3 px-5 py-4 text-xs"><span className="font-semibold text-[#ddd]">{department.name}</span><span className="text-[#888]">{department.active} active</span><span className="text-savannah">{department.present} present</span><span className="text-sunset">{department.absent} absent</span></div>)}</div> : <p className="px-5 py-10 text-center text-xs text-[#777]">No departments configured.</p>}</div></section>}</div>;
}
